title:               Harsh Vakharia

# site url without a trailing '/'
# i.e. http://www.example.com
url:                 http://harshjv.github.io

keywords:            'web, android, technology, docker, php, java, python, blog, computer engineering, surat, gujarat, india'
keywords_suffix:     ', harshjv, harsh vakharia'

# baseurl without a trailing '/'
# i.e. /my_project or leave it blank ''
baseurl:             ''
description:         Thoughts on technical stuff

paginate_path:       /blog/page/:num/
paginate:            15

permalink:           /blog/:title/

author:
  name:              Harsh Vakharia
  # Plain email or encoded email (http://ctrlq.org/encode/)
  email:
    id:              "harshjv@gmail.com"
    htmlencode:      "&#104;&#097;&#114;&#115;&#104;&#106;&#118;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
  docker:
    username:        harshjv
    link:            https://hub.docker.com/u/harshjv
  stackexchange:
    link:            http://stackexchange.com/users/1961153/harsh-vakharia?tab=accounts
  google_plus:
    username:        HarshVakhariaJ
    link:            https://plus.google.com/+HarshVakhariaJ
  linkedin:
    username:        harshjv
    link:            https://linkedin.com/in/harshjv
  angellist:
    username:        harshjv
    link:            https://angel.co/harshjv
  twitter:
    username:        harshjv
    link:            https://twitter.com/harshjv
  github:
    username:        harshjv
    link:            https://github.com/harshjv
  reddit:
    username:        harshjv
    link:            https://www.reddit.com/user/harshjv

disqus:
  shortname:         harshjv

# your analytics id
google_analytics:
  id:                UA-60794187-1

sass:
  sass_dir:          _sass
  style:             :compressed

the_wall:
  link:              https://github.com/the-wall/butler

exclude:             [vendor]

gems:
  - jekyll-sitemap
